/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as SolarRouteImport } from './routes/solar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolarIndexRouteImport } from './routes/solar.index'
import { Route as SolarStatisticsRouteImport } from './routes/solar.statistics'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarRoute = SolarRouteImport.update({
  id: '/solar',
  path: '/solar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarIndexRoute = SolarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolarRoute,
} as any)
const SolarStatisticsRoute = SolarStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => SolarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/solar': typeof SolarRouteWithChildren
  '/weather': typeof WeatherRoute
  '/solar/statistics': typeof SolarStatisticsRoute
  '/solar/': typeof SolarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/weather': typeof WeatherRoute
  '/solar/statistics': typeof SolarStatisticsRoute
  '/solar': typeof SolarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/solar': typeof SolarRouteWithChildren
  '/weather': typeof WeatherRoute
  '/solar/statistics': typeof SolarStatisticsRoute
  '/solar/': typeof SolarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/solar' | '/weather' | '/solar/statistics' | '/solar/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/weather' | '/solar/statistics' | '/solar'
  id: '__root__' | '/' | '/solar' | '/weather' | '/solar/statistics' | '/solar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SolarRoute: typeof SolarRouteWithChildren
  WeatherRoute: typeof WeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar': {
      id: '/solar'
      path: '/solar'
      fullPath: '/solar'
      preLoaderRoute: typeof SolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar/': {
      id: '/solar/'
      path: '/'
      fullPath: '/solar/'
      preLoaderRoute: typeof SolarIndexRouteImport
      parentRoute: typeof SolarRoute
    }
    '/solar/statistics': {
      id: '/solar/statistics'
      path: '/statistics'
      fullPath: '/solar/statistics'
      preLoaderRoute: typeof SolarStatisticsRouteImport
      parentRoute: typeof SolarRoute
    }
  }
}

interface SolarRouteChildren {
  SolarStatisticsRoute: typeof SolarStatisticsRoute
  SolarIndexRoute: typeof SolarIndexRoute
}

const SolarRouteChildren: SolarRouteChildren = {
  SolarStatisticsRoute: SolarStatisticsRoute,
  SolarIndexRoute: SolarIndexRoute,
}

const SolarRouteWithChildren = SolarRoute._addFileChildren(SolarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SolarRoute: SolarRouteWithChildren,
  WeatherRoute: WeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
